// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ClientMessages
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Move : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Move GetRootAsMove(ByteBuffer _bb) { return GetRootAsMove(_bb, new Move()); }
  public static Move GetRootAsMove(ByteBuffer _bb, Move obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Move __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ClientMessages.vector Pos { get { int o = __p.__offset(4); return o != 0 ? (ClientMessages.vector)__p.bb.GetSbyte(o + __p.bb_pos) : ClientMessages.vector.Zero; } }

  public static Offset<ClientMessages.Move> CreateMove(FlatBufferBuilder builder,
      ClientMessages.vector pos = ClientMessages.vector.Zero) {
    builder.StartTable(1);
    Move.AddPos(builder, pos);
    return Move.EndMove(builder);
  }

  public static void StartMove(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPos(FlatBufferBuilder builder, ClientMessages.vector pos) { builder.AddSbyte(0, (sbyte)pos, 0); }
  public static Offset<ClientMessages.Move> EndMove(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ClientMessages.Move>(o);
  }
  public static void FinishMoveBuffer(FlatBufferBuilder builder, Offset<ClientMessages.Move> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMoveBuffer(FlatBufferBuilder builder, Offset<ClientMessages.Move> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
