// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace messages_shot
{

public enum weapon_type : sbyte
{
  laser = 0,
  melee = 1,
};


}
