// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ServerMessages
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Game_Object : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Game_Object __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Id { get { return __p.bb.Get(__p.bb_pos + 0); } }
  public byte ObjType { get { return __p.bb.Get(__p.bb_pos + 1); } }
  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<ServerMessages.Game_Object> CreateGame_Object(FlatBufferBuilder builder, byte Id, byte ObjType, float X, float Y) {
    builder.Prep(4, 12);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    builder.Pad(2);
    builder.PutByte(ObjType);
    builder.PutByte(Id);
    return new Offset<ServerMessages.Game_Object>(builder.Offset);
  }
};


}
