// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Main_message
{

public enum mes_type : byte
{
  Register = 0,
  Move = 1,
};


}
