// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Main_message
{

public enum message_type : byte
{
  Register = 0,
  Ping = 1,
  Pong = 2,
  Answer = 3,
  Move = 4,
  Shot = 5,
  State = 6,
};


}
